name: snaketest
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base
    - r-irkernel=1.1
    - r-devtools
    - snakemake-minimal=5.8.1
    - mamba
    - bwa
    - samtools=1.10
    - bcftools
